### ISSUE TITLE
Linkni ichida button bo`lishi mumkin emas

### ISSUE THREAD

**Issue by yuldoshevgg** [omon490/youtube#3]
![image](https://user-images.githubusercontent.com/70746136/103505981-7c67fb80-4e7d-11eb-85b3-ec96bd1e4444.png)

**Comment by omon490** [comment]
Rahmat, to'g'irladim))
![image](https://user-images.githubusercontent.com/71442262/103794628-c3fdab80-5066-11eb-88ae-b5910a71cb49.png)
