### ISSUE TITLE
#mistake

### ISSUE THREAD

**Issue by Muhammadbobur3** [omon490/youtube#4]
194 va 195 qatorda section bor va uning ichida div bor bu joyda div kerak emas yoki section ikkinchi masala shu sectionni ichida heading berib qoyilmagan masuliyati cheklanganlar uchun qulayroq bo'lardi
![image](https://user-images.githubusercontent.com/71442221/103510185-804c4b80-4e86-11eb-882b-67429934bb9f.png)

**Comment by omon490** [comment]
To'g'irlandi rahmat))
