### ISSUE TITLE
#sass

### ISSUE THREAD

**Issue by Muhammadbobur3** [omon490/youtube#5]
Shu joyda bodyga class berilgan va u block papka ichida emas scss faylda ochilgan nazarimda bu ham blocks papkada ochilishi kerak chunki uning ichida menu-bar degan class ham bor ekan 
![image](https://user-images.githubusercontent.com/71442221/103510653-75de8180-4e87-11eb-8fba-1463d33096b9.png)

**Comment by omon490** [comment]
Rahmat, BEM bo'yicha siz aytgan usulda bo'lishi kerak edi))
